package(default_visibility = ["//visibility:public"])

java_library(
    name = "puzzles",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/java/algo/datastructures:datastructures",
        "//src/java/algo/datastructures/tree:tree",
    ],
)