package(default_visibility = ["//visibility:public"])

java_library(
    name = "graph",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/java/algo/datastructures:datastructures",
    ],
)