package(default_visibility = ["//visibility:public"])

java_library(
    name = "tree",
    srcs = glob(
        ["*.java"],
        allow_empty = True,  # This allows empty glob results
    ),
    deps = [
        "@maven//:com_google_guava_guava",
    ],
)