package(default_visibility = ["//visibility:public"])

java_library(
    name = "datastructures",
    srcs = glob([
        "*.java",
    ]),
    deps = [
        "//src/java/algo/algorithm/hash:hash",
        "@maven//:com_google_guava_guava",
    ],
)